# Generated by Django 5.2.8 on 2025-11-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuralQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('technique', models.CharField(help_text='Ej: Pintura acrílica, aerosol, etc.', max_length=200, verbose_name='Técnica')),
                ('dimensions', models.CharField(help_text='Ej: 3m x 2m, 5m x 4m, etc.', max_length=200, verbose_name='Dimensiones')),
                ('message', models.TextField(help_text='Describe tu proyecto o cualquier detalle adicional', verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Cotización de Mural',
                'verbose_name_plural': 'Cotizaciones de Murales',
                'ordering': ['-created_at'],
            },
        ),
    ]
