# Generated by Django 5.2.4 on 2025-11-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galeria', '0003_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_bio', models.TextField(blank=True)),
                ('featured_video_url', models.URLField(blank=True)),
                ('featured_painting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='galeria.painting')),
            ],
        ),
    ]
