# Generated by Django 5.2.4 on 2025-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mural',
            name='dimensions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mural',
            name='is_for_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mural',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mural',
            name='technique',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mural',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
