# Generated by Django 5.2.4 on 2025-11-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mural', '0002_mural_dimensions_mural_is_for_sale_mural_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mural',
            name='is_for_sale',
        ),
        migrations.RemoveField(
            model_name='mural',
            name='price',
        ),
    ]
