# Generated by Django 5.2.4 on 2025-11-20 18:11

import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_painting_dimensions_painting_is_for_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=galeria.models.submission_image_upload_to)),
                ('category', models.CharField(choices=[('painting', 'Pintura'), ('mural', 'Mural')], default='painting', max_length=20)),
                ('technique', models.CharField(blank=True, max_length=200)),
                ('dimensions', models.CharField(blank=True, max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_for_sale', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Envío público',
                'verbose_name_plural': 'Envíos públicos',
            },
        ),
    ]
