# Generated by Django 5.2.4 on 2025-11-27 18:06

import galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(choices=[('painting', 'Pintura'), ('mural', 'Mural')], default='painting', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dimensions',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dimensiones'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=galeria.models.submission_image_upload_to, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_for_sale',
            field=models.BooleanField(default=True, verbose_name='En venta'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='technique',
            field=models.CharField(blank=True, max_length=200, verbose_name='Técnica'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
    ]
