# Generated by Django 5.2.8 on 2025-11-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_submission_approved_alter_submission_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='category',
            field=models.CharField(choices=[('pintura', 'Pintura'), ('ilustracion', 'Ilustración')], default='pintura', max_length=20, verbose_name='Categoría'),
        ),
    ]
